name: snyk-cron
on:
  workflow_dispatch: {}
  schedule:
    # trigger on schedule once a day
    - cron: "0 0 * * *"
jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor